const {GoogleGenAI, Type} = require("@google/genai")
const chromium = require("@sparticuz/chromium");
const puppeteer = require("puppeteer-core");

console.log("CHROMIUM =", chromium);
console.log("TYPE =", typeof chromium);
console.log("EXECUTABLE PATH =", chromium.executablePath);

const ai = new GoogleGenAI({
    apiKey: process.env.GoogleGenAI_API
});


const questionSchema = {
    type: Type.OBJECT,
    properties: {
        question: { type: Type.STRING },
        intention: { type: Type.STRING },
        answer: { type: Type.STRING }
    },
    required: ["question", "intention", "answer"]
}

const interviewReportSchema = {
    type: Type.OBJECT,
    properties: {
        title: { type: Type.STRING },
        matchScore: { type: Type.NUMBER },
        technicalQuestions: {
            type: Type.ARRAY,
            items: questionSchema
        },
        behavioralQuestions: {
            type: Type.ARRAY,
            items: questionSchema
        },
        skillGaps: {
            type: Type.ARRAY,
            items: {
                type: Type.OBJECT,
                properties: {
                    skill: { type: Type.STRING },
                    severity: {
                        type: Type.STRING,
                        enum: ["low", "medium", "high"]
                    }
                },
                required: ["skill", "severity"]
            }
        },
        preparationPlan: {
            type: Type.ARRAY,
            items: {
                type: Type.OBJECT,
                properties: {
                    day: { type: Type.NUMBER },
                    focus: { type: Type.STRING },
                    tasks: {
                        type: Type.ARRAY,
                        items: { type: Type.STRING }
                    }
                },
                required: ["day", "focus", "tasks"]
            }
        }
    },
    required: [
        "title",
        "matchScore",
        "technicalQuestions",
        "behavioralQuestions",
        "skillGaps",
        "preparationPlan"
    ]
}

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {
const prompt = `
Return ONLY JSON in exactly this format:
At least 5 technical and 5 behavioral questions with their model answers and intentions. Match score should be out of 100 and should reflect how well the candidate is fit for the job based on the provided information. Preparation plan should be of 14 days with clear focus and tasks for each day. Title should be a concise summary of the report.
{
  "matchScore": 85,
  "technicalQuestions": [
    {
      "question": "...",
      "intention": "...",
      "answer": "..."
    }
  ],
  "behavioralQuestions": [
    {
      "question": "...",
      "intention": "...",
      "answer": "..."
    }
  ],
  "skillGaps": [
    {
      "skill": "...",
      "severity": "low"
    }
  ],
  "preparationPlan": [
    {
      "day": 1,
      "focus": "...",
      "tasks": ["...", "..."]
    }
  ],
  "title": "..."
}

            Resume:
            ${resume}

            Self Description:
            ${selfDescription || "Not provided"}

Job Description:
${jobDescription}
`;

    const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: interviewReportSchema,
        }
    })

    return JSON.parse(response.text)

}

async function generateResumePdf({resume, selfDescription, jobDescription}){

    const browser = await puppeteer.launch({
            args: chromium.args,
            executablePath: await chromium.executablePath(),
            headless: true
        });
    const page = await browser.newPage()
    const resumePdfSchema = {
  type: "object",
  properties: {
    html: {
      type: "string",
      description: "HTML content of the resume which can be converted to PDF using Puppeteer"
    }
  },
  required: ["html"]
};

    const prompt = `Generate a resume for the following candidate based on his resume content, self description and job description. Return only JSON in the following format and make sure html content is well formatted so that it can be directly converted to pdf using puppeteer.
    The Content of resume should not sound like its generated by AI and should be crisp, clear and to the point. Avoid adding unnecessary details in the resume and it should be strictly one page.
    Also highlight the skills with different font styles in the resume which are required in the job description.
    Try not to leave space at the end of the page and make sure the content is well formatted to utilize the whole page.

    Resume:
    ${resume}

    Self Description:
    ${selfDescription || "Not provided"}

    Job Description:
    ${jobDescription}

    `

    const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        config: {
            responseMimeType: "application/json",
            responseSchema: resumePdfSchema
        },
        contents: prompt
     })

     const jsonContent = JSON.parse(response.text)

     await page.setContent(jsonContent.html, {waitUntil: "domcontentloaded"});
     const pdfBuffer = await page.pdf({ format: "A4", margin: { top: "15mm", bottom: "15mm", left: "10mm", right: "10mm" } })

     await browser.close()

     return pdfBuffer

}




module.exports = { generateInterviewReport, generateResumePdf } 